# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-15 12:59
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_isleifpoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isleifpoints',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='isleifpoints',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='isleifpoints',
            name='name',
        ),
        migrations.RemoveField(
            model_name='isleifpoints',
            name='point',
        ),
        migrations.AddField(
            model_name='isleifpoints',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='isleifpoints',
            name='samtala',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='isleifpoints',
            name='x',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='isleifpoints',
            name='y',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
