# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-25 13:18
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_auto_20190915_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isleifpoints',
            name='x',
        ),
        migrations.RemoveField(
            model_name='isleifpoints',
            name='y',
        ),
        migrations.AlterField(
            model_name='isleifpoints',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
